import type { Metadata, Viewport } from "next";
import { Fraunces, Inter } from "next/font/google";
import "./globals.css";
import { publicEnv } from "@/lib/env";

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-display",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

const siteUrl = publicEnv.siteUrl;
const siteName = publicEnv.siteName;
const fee = publicEnv.assessmentFeeDisplay;
const description =
  `Dr. Aditya runs your fasting insulin, HOMA-IR, cortisol, and gut markers first, finds the exact metabolic breakdown, then builds everything around it. Restore your cycles, lose stubborn weight, and clear your skin in 90 days. Physician-led PCOS programme with therapeutic IV infusion. Assessment from ${fee}.`;

/**
 * Root metadata. Page files that are "use client" (landing/checkout/book-a-call)
 * inherit from here. Static server pages (thank-you, terms, privacy, refund)
 * override via their own `export const metadata`.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "The PCOS Metabolic Assessment for the Woman Who Has Tried Everything",
    template: "%s · Dr. Aditya & Akhila",
  },
  description,
  keywords: [
    "PCOS programme India",
    "PCOS root cause treatment",
    "insulin resistance PCOS",
    "PCOS metabolic assessment",
    "IV infusion PCOS",
    "Dr. Aditya PCOS",
    "Akhila nutritionist PCOS",
    "PCOS without pills",
    "PCOS fertility India",
    "HOMA-IR cortisol PCOS",
  ],
  authors: [{ name: "Dr. Aditya & Akhila" }],
  creator: "Dr. Aditya & Akhila",
  publisher: "Dr. Aditya & Akhila Clinical Team",
  alternates: { canonical: "/" },
  category: "health",
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: siteUrl,
    siteName,
    title: "For the Woman Who Has Tried Everything. Except the Right Diagnosis.",
    description,
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "The PCOS Metabolic Assessment by Dr. Aditya & Akhila",
    description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FDFBF7" },
    { media: "(prefers-color-scheme: dark)", color: "#5A1E30" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

/**
 * GLOBAL UTM CAPTURE
 * ------------------
 * Reads utm_source / utm_medium / utm_campaign / fbclid / gclid / etc. from
 * the URL on every page load and persists them to sessionStorage + a 30-day
 * cookie so the entire funnel (landing → checkout → book-a-call → thank-you)
 * carries the attribution.
 *
 * Inlined here (vs a separate client component) so the funnel "brain" lives
 * in one global place. Modify the list below to add/remove tracked params.
 */
const UTM_CAPTURE_SNIPPET = `
(function(){
  try {
    var keys = ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','utm_id','fbclid','gclid','wbraid','gbraid','ttclid','msclkid','ref'];
    var url = new URL(window.location.href);
    var found = {};
    keys.forEach(function(k){
      var v = url.searchParams.get(k);
      if (v) found[k] = v;
    });
    var existing = {};
    try {
      var raw = sessionStorage.getItem('akhila_utm_v1');
      if (raw) existing = JSON.parse(raw);
    } catch(e) {}
    if (!Object.keys(existing).length) {
      var m = document.cookie.match(/(?:^|; )akhila_utm_v1=([^;]*)/);
      if (m) { try { existing = JSON.parse(decodeURIComponent(m[1])); } catch(e) {} }
    }
    var merged = Object.assign({}, existing, found);
    if (Object.keys(merged).length) {
      try { sessionStorage.setItem('akhila_utm_v1', JSON.stringify(merged)); } catch(e) {}
      var days = 30;
      var expires = new Date(Date.now() + days*864e5).toUTCString();
      var secure = window.location.protocol === 'https:' ? '; Secure' : '';
      document.cookie = 'akhila_utm_v1=' + encodeURIComponent(JSON.stringify(merged)) + '; Expires=' + expires + '; Path=/; SameSite=Lax' + secure;
    }
  } catch(e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${inter.variable}`}>
      <head>
        <link rel="preconnect" href="https://checkout.razorpay.com" />
        <link rel="dns-prefetch" href="https://checkout.razorpay.com" />
        {/* JSON-LD: Medical Business + Person schema for SEO/AEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "MedicalBusiness",
              name: "Dr. Aditya & Akhila's PCOS Metabolic Programme",
              url: siteUrl,
              description,
              medicalSpecialty: ["Endocrine", "FamilyPractice", "Nutrition"],
              priceRange: "₹₹₹",
              areaServed: "IN",
              offers: {
                "@type": "Offer",
                name: "PCOS Metabolic Assessment",
                price: String(publicEnv.assessmentFeeInr),
                priceCurrency: "INR",
                availability: "https://schema.org/InStock",
              },
              employee: [
                {
                  "@type": "Physician",
                  name: "Dr. Aditya",
                  jobTitle: "Senior Family Physician",
                  medicalSpecialty: "FamilyPractice",
                },
                {
                  "@type": "Person",
                  name: "Akhila",
                  jobTitle: "Clinical Nutritionist",
                },
              ],
            }),
          }}
        />
        {/* Global UTM capture — runs on every page load before React hydrates */}
        <script dangerouslySetInnerHTML={{ __html: UTM_CAPTURE_SNIPPET }} />
      </head>
      <body className="min-h-screen bg-cream-50 antialiased">{children}</body>
    </html>
  );
}
