import type { Metadata, Viewport } from "next";
import { Fraunces, Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { publicEnv } from "@/lib/env";
import { MetaPageView } from "@/components/MetaPageView";

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-display",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

const siteUrl = publicEnv.siteUrl;
const siteName = publicEnv.siteName;
const fee = publicEnv.assessmentFeeDisplay;
const description =
  `Dr. Aditya maps your full metabolic picture first, finds what's actually holding your body back, then builds your 90-day plan around it. Get your energy and rhythm back. Expert-led, root-cause programme. Assessment from ${fee}.`;

/**
 * Root metadata. Page files that are "use client" (landing/checkout/book-a-call)
 * inherit from here. Static server pages (thank-you, terms, privacy, refund)
 * override via their own `export const metadata`.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "The Metabolic Reset for the Woman Who Has Tried Everything",
    template: "%s · Dr. Aditya & Akhila",
  },
  description,
  authors: [{ name: "Dr. Aditya & Akhila" }],
  creator: "Dr. Aditya & Akhila",
  publisher: "Dr. Aditya & Akhila",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: siteUrl,
    siteName,
    title: "For the Woman Who Has Tried Everything. Except the Root Cause.",
    description,
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "The Metabolic Reset by Dr. Aditya & Akhila",
    description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FDFBF7" },
    { media: "(prefers-color-scheme: dark)", color: "#D26C3C" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

/**
 * GLOBAL UTM CAPTURE
 * ------------------
 * Reads utm_source / utm_medium / utm_campaign / fbclid / gclid / etc. from
 * the URL on every page load and persists them to sessionStorage + a 30-day
 * cookie so the entire funnel (landing → checkout → book-a-call → thank-you)
 * carries the attribution.
 *
 * Inlined here (vs a separate client component) so the funnel "brain" lives
 * in one global place. Modify the list below to add/remove tracked params.
 */
const UTM_CAPTURE_SNIPPET = `
(function(){
  try {
    var keys = ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','utm_id','fbclid','gclid','wbraid','gbraid','ttclid','msclkid','ref'];
    var url = new URL(window.location.href);
    var found = {};
    keys.forEach(function(k){
      var v = url.searchParams.get(k);
      if (v) found[k] = v;
    });
    var existing = {};
    try {
      var raw = sessionStorage.getItem('akhila_utm_v1');
      if (raw) existing = JSON.parse(raw);
    } catch(e) {}
    if (!Object.keys(existing).length) {
      var m = document.cookie.match(/(?:^|; )akhila_utm_v1=([^;]*)/);
      if (m) { try { existing = JSON.parse(decodeURIComponent(m[1])); } catch(e) {} }
    }
    var merged = Object.assign({}, existing, found);
    // First-touch attribution snapshot: landing_url + referrer. Only written
    // on the FIRST page in the session (never overwritten on subsequent
    // navigations) so the values describe how the visitor arrived, not
    // where they currently are. Truncated to 240 chars so the values fit
    // within Razorpay's 256-char-per-note-value limit when forwarded later.
    if (!existing.landing_url) {
      merged.landing_url = window.location.href.slice(0, 240);
    }
    if (!('referrer' in existing)) {
      var ref = document.referrer || '';
      merged.referrer = ref.slice(0, 240);
    }
    if (Object.keys(merged).length) {
      try { sessionStorage.setItem('akhila_utm_v1', JSON.stringify(merged)); } catch(e) {}
      var days = 30;
      var expires = new Date(Date.now() + days*864e5).toUTCString();
      var secure = window.location.protocol === 'https:' ? '; Secure' : '';
      document.cookie = 'akhila_utm_v1=' + encodeURIComponent(JSON.stringify(merged)) + '; Expires=' + expires + '; Path=/; SameSite=Lax' + secure;
    }
  } catch(e) {}
})();
`;

/**
 * META PIXEL — cookie-aware init + first PageView
 * -----------------------------------------------
 * Loads fbevents.js, then BEFORE firing the initial PageView:
 *   1. Reads the persistent `akhila_mam` cookie (written by
 *      setMetaAdvancedMatching in src/lib/analytics.ts after form-fill).
 *   2. If the cookie holds hashed Advanced Matching values, re-inits the
 *      pixel with them so every PageView in this document — including
 *      cold visits from returning users up to 30 days later — ships with
 *      em / ph / fn / ln / ct / country / external_id attached.
 *   3. Fires PageView once for the initial document load. Subsequent
 *      App-Router client-side navigations are handled by <MetaPageView/>.
 *
 * Inlined here (not as a separate <Script>) so the pixel installs and the
 * cookie is read in <head>, BEFORE React hydrates and before any other
 * client code runs. This is what makes returning-user EMQ jump from ~6
 * (cold) to ~8 (cookie-restored identity).
 *
 * Empty pixel id → snippet does nothing (gated below in JSX). No
 * NEXT_PUBLIC_META_PIXEL_ID means Meta tracking is disabled cleanly.
 */
const META_PIXEL_ID = publicEnv.metaPixelId;
const META_PROD_HOSTNAME = publicEnv.prodHostname;
/**
 * Pixel snippet is wrapped in a hostname guard so it does NOTHING on
 * Vercel preview deployments, localhost, or any other non-prod host.
 * The guard is the same value used by src/lib/gating.ts on the server
 * and isProductionDomain() in src/lib/analytics.ts on the client.
 * To enable the pixel locally for debugging, point NEXT_PUBLIC_SITE_URL
 * at http://localhost:3000 and restart dev — the hostname will then
 * match and fbq will fire.
 */
const META_PIXEL_SNIPPET = META_PIXEL_ID
  ? `
(function(){
  if (window.location.hostname.toLowerCase() !== '${META_PROD_HOSTNAME}') return;
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '${META_PIXEL_ID}');
  try {
    var m = document.cookie.match(/(?:^|;\\s*)akhila_mam=([^;]+)/);
    if (m) {
      var mam = JSON.parse(decodeURIComponent(m[1]));
      if (mam && typeof mam === 'object' && Object.keys(mam).length) {
        fbq('init', '${META_PIXEL_ID}', mam);
      }
    }
  } catch (e) {}
  fbq('track', 'PageView');
  // Token: tells MetaPageView "I just fired PageView for this pathname".
  // Without this, the inline-script PageView on cold load + MetaPageView's
  // first-mount useEffect would BOTH fire for the landing pathname → one
  // page view counted twice in Events Manager.
  try {
    window.__akhila_last_pv = { pathname: location.pathname, at: Date.now() };
  } catch (e) {}
})();
`
  : "";

/**
 * GOOGLE ANALYTICS 4 + MICROSOFT CLARITY
 * ---------------------------------------
 * Vendor-neutral analytics (NOT Meta). Hard-gated to the production hostname —
 * the same guard as the Meta pixel — so localhost dev and Vercel previews send
 * ZERO hits and never pollute GA4 reports or Clarity session recordings. The
 * IDs are public (visible in page source), so they live as literals here;
 * setting either to "" cleanly disables that tracker.
 */
const GA4_MEASUREMENT_ID: string = "G-08N5C538K1";
const CLARITY_PROJECT_ID: string = "x1rh78gic1";

const GA4_SNIPPET = GA4_MEASUREMENT_ID
  ? `
(function(){
  if (window.location.hostname.toLowerCase() !== '${META_PROD_HOSTNAME}') return;
  var s = document.createElement('script');
  s.async = true;
  s.src = 'https://www.googletagmanager.com/gtag/js?id=${GA4_MEASUREMENT_ID}';
  document.head.appendChild(s);
  window.dataLayer = window.dataLayer || [];
  function gtag(){ window.dataLayer.push(arguments); }
  window.gtag = gtag;
  gtag('js', new Date());
  gtag('config', '${GA4_MEASUREMENT_ID}');
})();
`
  : "";

const CLARITY_SNIPPET = CLARITY_PROJECT_ID
  ? `
(function(){
  if (window.location.hostname.toLowerCase() !== '${META_PROD_HOSTNAME}') return;
  (function(c,l,a,r,i,t,y){
    c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
    t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
    y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
  })(window, document, "clarity", "script", "${CLARITY_PROJECT_ID}");
})();
`
  : "";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${inter.variable}`}>
      <head>
        <link rel="preconnect" href="https://checkout.razorpay.com" />
        <link rel="dns-prefetch" href="https://checkout.razorpay.com" />
        {/* JSON-LD: neutral Organization schema. Deliberately NOT a
            MedicalBusiness / Physician / medicalSpecialty schema — that is a
            machine-readable "health condition" signal Meta reads when it
            classifies the dataset (see META_HW_HARDENING.md). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Dr. Aditya & Akhila's Metabolic Programme",
              url: siteUrl,
              description,
              areaServed: "IN",
              offers: {
                "@type": "Offer",
                name: "Metabolic Assessment",
                price: String(publicEnv.assessmentFeeInr),
                priceCurrency: "INR",
                availability: "https://schema.org/InStock",
              },
              founder: [
                { "@type": "Person", name: "Dr. Aditya" },
                { "@type": "Person", name: "Akhila" },
              ],
            }),
          }}
        />
        {/* Global UTM capture — runs on every page load before React hydrates */}
        <script dangerouslySetInnerHTML={{ __html: UTM_CAPTURE_SNIPPET }} />
        {/* Meta Pixel — installs fbq, re-applies cookie-persisted MAM, then
            fires the first PageView. All gated on NEXT_PUBLIC_META_PIXEL_ID. */}
        {META_PIXEL_ID && (
          <script dangerouslySetInnerHTML={{ __html: META_PIXEL_SNIPPET }} />
        )}
        {/* Google Analytics 4 — prod-host gated (vendor-neutral, not Meta) */}
        {GA4_SNIPPET && (
          <script dangerouslySetInnerHTML={{ __html: GA4_SNIPPET }} />
        )}
        {/* Microsoft Clarity — prod-host gated (vendor-neutral, not Meta) */}
        {CLARITY_SNIPPET && (
          <script dangerouslySetInnerHTML={{ __html: CLARITY_SNIPPET }} />
        )}
      </head>
      <body className="min-h-screen bg-cream-50 antialiased">
        {children}
        {/* JS-disabled fallback for the Meta Pixel — server-side <img> hit so
            even no-JS visitors register a PageView. No MAM, no event_id. */}
        {META_PIXEL_ID && (
          <noscript>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              height="1"
              width="1"
              style={{ display: "none" }}
              alt=""
              src={`https://www.facebook.com/tr?id=${META_PIXEL_ID}&ev=PageView&noscript=1`}
            />
          </noscript>
        )}
        {/* App-Router client-side PageView tracker. Suspense boundary required
            because MetaPageView calls useSearchParams(). */}
        {META_PIXEL_ID && (
          <Suspense fallback={null}>
            <MetaPageView />
          </Suspense>
        )}
      </body>
    </html>
  );
}
